ALTER TABLE tasks ADD created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '作成日時'; -- DATETIME(3)はMySQL 5.6.4以降でサポートされているミリ秒精度の日時型
ALTER TABLE tasks ADD updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新日時';
